defaults: &defaults
  mailgun:
    apiKey: "needs to come from env variable"
    url: ""
    domain: ""
  sendgrid:
    apiKey: ""
    url: ""
  primary: sendgrid

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
